#define BRUTE_FORCE 1
#define RESOLUTION 8192
#define TEXELS_NORMAL 1
#define PADDING 0
#define TRANSPOSE 0

#define COARSE_STEPS 2
#define ROTATION 0
#define SKIP_SPEEDUP 0
#define GRID_SPEEDUP 0
#define PREV_POSITION_OFFSET 0.f
#define PARALLEL 0

#define BLOCK_ALIGN 0
